name: Portman Tests

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      PIPELINE_EXECUTION_ROLE:
        required: true
        type: string

jobs:
  portman:
    name: Run Portman
    runs-on: ubuntu-latest
    environment: {{ '${{ inputs.ENVIRONMENT }}' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: {{ '${{ inputs.AWS_REGION }}' }}
          role-to-assume: {{ '${{ inputs.PIPELINE_EXECUTION_ROLE }}' }}
          role-session-name: testing-packaging
          role-duration-seconds: 3600
          role-skip-session-tagging: true
      - run: npm install -g @apideck/portman
      - run: npm ci
      - name: Test API
        run: |
          aws cloudformation describe-stacks --stack-name task-service-api --query "Stacks[0].Outputs[?OutputKey=='ApiURL'].OutputValue" --output text
          npm run set-portman-config ./portman/portman-config.json ./portman/portman-cli.json {{ '${{ inputs.ENVIRONMENT }}' }}
          npm run portman