version = 0.1
[api]
[api.deploy]
[api.deploy.parameters]
stack_name = "{{ cookiecutter.stack_name }}"
capabilities = "CAPABILITY_IAM"

[dynamodb]
[dynamodb.deploy]
[dynamodb.deploy.parameters]
stack_name = "{{ cookiecutter.stack_name }}-dynamodb"
capabilities = "CAPABILITY_IAM"

[default.build]
[default.build.parameters]
cached="true"
parallel="true"