version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "{{ cookiecutter.stack_name }}"
capabilities = "CAPABILITY_IAM"

[default.build]
[default.build.parameters]
cached="true"
parallel="true"